name: EasyScan
description: A Crossplatform document scanning app that can convert images to pdf in a simple tap.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^1.9.0
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+4
  flutter_image_editor: ^1.2.0

flutter:
  uses-material-design: true
